//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flights
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Flights()
        {
            this.Tickets = new HashSet<Tickets>();
        }
    
        public int Flight_Number { get; set; }
        public Nullable<System.DateTime> Fly_Date { get; set; }
        public Nullable<System.TimeSpan> Fly_Time { get; set; }
        public Nullable<int> Fly_Town { get; set; }
        public Nullable<System.DateTime> Arrival_Date { get; set; }
        public Nullable<int> Arrival_Town { get; set; }
        public Nullable<System.TimeSpan> Arrival_Time { get; set; }
        public Nullable<int> Aircraft_Number { get; set; }
    
        public virtual Aircraft1 Aircraft1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tickets> Tickets { get; set; }
        public virtual Town Town { get; set; }
        public virtual Town Town1 { get; set; }
    }
}
