//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Places
    {
        public int Place_Number { get; set; }
        public int Row_Number { get; set; }
        public int Aircraft_Number { get; set; }
    
        public virtual Aircraft1 Aircraft1 { get; set; }
    }
}
