//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovoy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int Ticket_Number { get; set; }
        public Nullable<int> Passenger_Number { get; set; }
        public Nullable<int> Airline_Number { get; set; }
        public Nullable<int> Flight_Number { get; set; }
        public Nullable<int> Place_Number { get; set; }
        public Nullable<int> Row_Number { get; set; }
        public Nullable<int> Aircraft_Number { get; set; }
    
        public virtual Flights Flights { get; set; }
        public virtual Passengers Passengers { get; set; }
    }
}
